
#define LINE_WIDTH          64
#define MNEMONIC_POS        48

class Disasm {
    public:
    enum MNEMONIC {
        zADC,  zADD,  zAND,  zBIT,  zCALL, zCCF,  zCP,   zCPD,
        zCPDR, zCPI,  zCPIR, zCPL,  zDAA,  zDB,   zDEC,  zDI,
        zDJNZ, zEI,   zEX,   zEXX,  zHLT,  zIM,   zIN,   zINC,
        zIND,  zINDR, zINI,  zINIR, zJP,   zJR,   zLD,   zLDD,
        zLDDR, zLDI,  zLDIR, zNEG,  zNOP,  zOR,   zOTDR, zOTIR,
        zOUT,  zOUTD, zOUTI, zPOP,  zPUSH, zRES,  zRET,  zRETI,
        zRETN, zRL,   zRLA,  zRLC,  zRLCA, zRLD,  zRR,   zRRA,
        zRRC,  zRRCA, zRRD,  zRST,  zSBC,  zSCF,  zSET,  zSLA,
        zSLL,  zSRA,  zSRL,  zSUB,  zXOR
    };
    enum IDX_REG {
        IX, IY
    };

    struct Desc {
        MNEMONIC mnem;
        const char *p_op;
    };

        unsigned short dis(unsigned short ptr, Z80 *p_cpu, Memory *p_memory, bool show_info = true);
    private:
        char line[1024];
        const char *p_mnemonic[69] = {
            "ADC", "ADD", "AND", "BIT", "CALL", "CCF", "CP", "CPD",
            "CPDR", "CPI", "CPIR", "CPL", "DAA",  "DB",  "DEC", "DI",
            "DJNZ", "EI",  "EX",  "EXX", "HALT", "IM",  "IN", "INC",
            "IND", "INDR", "INI", "INIR", "JP",   "JR",  "LD", "LDD",
            "LDDR", "LDI", "LDIR", "NEG", "NOP",  "OR",  "OUTDR", "OTIR",
            "OUT", "OUTD", "OUTI", "POP", "PUSH", "RES", "RET", "RETI",
            "RETN", "RL",  "RLA", "RLC", "RLCA", "RLD", "RR", "RRA",
            "RRC", "RRCA", "RRD", "RST", "SBC",  "SCF", "SET", "SLA",
            "SLL", "SRA", "SRL", "SUB", "XOR"
        };
        const char *p_op16_1[4] =    { "BC", "DE", "HL", "SP" };
        const char *p_op16_2[4] =    { "BC", "DE", "HL", "AF" };
        const char *p_op8[8] =       { "B", "C", "D", "E", "H", "L", "(HL)", "A" };
        const char *p_flag[8] =      { "NZ", "Z", "NC", "C", "PO", "PE", "P", "M" };
        const char *p_idx_reg[2] =   { "IX", "IY" };

        Desc no_prefix[0x100] = {
            {zNOP, NULL},       {zLD, "p, w"},      {zLD, "(BC), A"},    {zINC, "p"},        {zINC, "y"},        {zDEC, "y"},        {zLD, "B, b"},      {zRLCA, NULL},
            {zEX, "AF, AF'"},   {zADD, "HL, p"},    {zLD, "A, (BC)"},    {zDEC, "p"},        {zINC, "y"},        {zDEC, "y"},        {zLD, "C, b"},      {zRRCA, NULL},
            {zDJNZ, "l"},       {zLD, "p, w"},      {zLD, "(DE), A"},    {zINC, "p"},        {zINC, "y"},        {zDEC, "y"},        {zLD, "D, b"},      {zRLA, NULL},
            {zJR, "c, l"},      {zADD, "HL, p"},    {zLD, "A, (DE)"},    {zDEC, "p"},        {zINC, "y"},        {zDEC, "y"},        {zLD, "E, b"},      {zRRA, NULL},
            {zJR, "c, l"},      {zLD, "p, w"},      {zLD, "(w), HL"},    {zINC, "p"},        {zINC, "y"},        {zDEC, "y"},        {zLD, "H, b"},      {zDAA, NULL},
            {zJR, "c, l"},      {zADD, "HL, p"},    {zLD, "HL, (w)"},    {zDEC, "p"},        {zINC, "y"},        {zDEC, "y"},        {zLD, "L, b"},      {zCPL, NULL},
            {zJR, "c, l"},      {zLD, "p, w"},      {zLD, "(w), A"},     {zINC, "p"},        {zINC, "y"},        {zDEC, "y"},        {zLD, "(HL), b"},   {zSCF, NULL},
            {zJR, "c, l"},      {zADD, "HL, p"},    {zLD, "A, (w)"},     {zDEC, "p"},        {zINC, "y"},        {zDEC, "y"},        {zLD, "A, b"},      {zCCF, NULL},
            {zLD, "y, z"},      {zLD, "y, z"},      {zLD, "y, z"},       {zLD, "y, z"},      {zLD, "y, z"},      {zLD, "y, z"},      {zLD, "y, z"},      {zLD, "y, z"},
            {zLD, "y, z"},      {zLD, "y, z"},      {zLD, "y, z"},       {zLD, "y, z"},      {zLD, "y, z"},      {zLD, "y, z"},      {zLD, "y, z"},      {zLD, "y, z"},
            {zLD, "y, z"},      {zLD, "y, z"},      {zLD, "y, z"},       {zLD, "y, z"},      {zLD, "y, z"},      {zLD, "y, z"},      {zLD, "y, z"},      {zLD, "y, z"},
            {zLD, "y, z"},      {zLD, "y, z"},      {zLD, "y, z"},       {zLD, "y, z"},      {zLD, "y, z"},      {zLD, "y, z"},      {zLD, "y, z"},      {zLD, "y, z"},
            {zLD, "y, z"},      {zLD, "y, z"},      {zLD, "y, z"},       {zLD, "y, z"},      {zLD, "y, z"},      {zLD, "y, z"},      {zLD, "y, z"},      {zLD, "y, z"},
            {zLD, "y, z"},      {zLD, "y, z"},      {zLD, "y, z"},       {zLD, "y, z"},      {zLD, "y, z"},      {zLD, "y, z"},      {zLD, "y, z"},      {zLD, "y, z"},
            {zLD, "y, z"},      {zLD, "y, z"},      {zLD, "y, z"},       {zLD, "y, z"},      {zLD, "y, z"},      {zLD, "y, z"},      {zHLT, NULL},       {zLD, "y, z"},
            {zLD, "y, z"},      {zLD, "y, z"},      {zLD, "y, z"},       {zLD, "y, z"},      {zLD, "y, z"},      {zLD, "y, z"},      {zLD, "y, z"},      {zLD, "y, z"},
            {zADD, "A, z"},     {zADD, "A, z"},     {zADD, "A, z"},      {zADD, "A, z"},     {zADD, "A, z"},     {zADD, "A, z"},     {zADD, "A, z"},     {zADD, "A, z"},
            {zADC, "A, z"},     {zADC, "A, z"},     {zADC, "A, z"},      {zADC, "A, z"},     {zADC, "A, z"},     {zADC, "A, z"},     {zADC, "A, z"},     {zADC, "A, z"},
            {zSUB, "z"},        {zSUB, "z"},        {zSUB, "z"},         {zSUB, "z"},        {zSUB, "z"},        {zSUB, "z"},        {zSUB, "z"},        {zSUB, "z"},
            {zSBC, "A, z"},     {zSBC, "A, z"},     {zSBC, "A, z"},      {zSBC, "A, z"},     {zSBC, "A, z"},     {zSBC, "A, z"},     {zSBC, "A, z"},     {zSBC, "A, z"},
            {zAND, "z"},        {zAND, "z"},        {zAND, "z"},         {zAND, "z"},        {zAND, "z"},        {zAND, "z"},        {zAND, "z"},        {zAND, "z"},
            {zXOR, "z"},        {zXOR, "z"},        {zXOR, "z"},         {zXOR, "z"},        {zXOR, "z"},        {zXOR, "z"},        {zXOR, "z"},        {zXOR, "z"},
            {zOR, "z"},         {zOR, "z"},         {zOR, "z"},          {zOR, "z"},         {zOR, "z"},         {zOR, "z"},         {zOR, "z"},         {zOR, "z"},
            {zCP, "z"},         {zCP, "z"},         {zCP, "z"},          {zCP, "z"},         {zCP, "z"},         {zCP, "z"},         {zCP, "z"},         {zCP, "z"},
            {zRET, "f"},        {zPOP, "i"},        {zJP, "f, w"},       {zJP, "w"},         {zCALL, "f, w"},    {zPUSH, "i"},       {zADD, "A, b"},     {zRST, "t"},
            {zRET, "f"},        {zRET, NULL},       {zJP, "f, w"},       {zDB, NULL},        {zCALL, "f, w"},    {zCALL, "w"},       {zADC, "A, b"},     {zRST, "t"},
            {zRET, "f"},        {zPOP, "i"},        {zJP, "f, w"},       {zOUT, "(b), A"},   {zCALL, "f, w"},    {zPUSH, "i"},       {zSUB, "b"},        {zRST, "t"},
            {zRET, "f"},        {zEXX, NULL},       {zJP, "f, w"},       {zIN, "A, (b)"},    {zCALL, "f, w"},    {zDB, NULL},        {zSBC, "A, b"},     {zRST, "t"},
            {zRET, "f"},        {zPOP, "i"},        {zJP, "f, w"},       {zEX, "(SP), HL"},  {zCALL, "f, w"},    {zPUSH, "i"},       {zAND, "b"},        {zRST, "t"},
            {zRET, "f"},        {zJP, "(HL)"},      {zJP, "f, w"},       {zEX, "DE, HL"},    {zCALL, "f, w"},    {zDB, NULL},        {zXOR, "b"},        {zRST, "t"},
            {zRET, "f"},        {zPOP, "i"},        {zJP, "f, w"},       {zDI, NULL},        {zCALL, "f, w"},    {zPUSH, "i"},       {zOR, "b"},         {zRST, "t"},
            {zRET, "f"},        {zLD, "SP, HL"},    {zJP, "f, w"},       {zEI, NULL},        {zCALL, "f, w"},    {zDB, NULL},        {zCP, "b"},         {zRST, "t"}
        };
        Desc cb_prefix[0x100] = {
            {zRLC, "z"},     {zRLC, "z"},     {zRLC, "z"},     {zRLC, "z"},
            {zRLC, "z"},     {zRLC, "z"},     {zRLC, "z"},     {zRLC, "z"},
            {zRRC, "z"},     {zRRC, "z"},     {zRRC, "z"},     {zRRC, "z"},
            {zRRC, "z"},     {zRRC, "z"},     {zRRC, "z"},     {zRRC, "z"},
            {zRL, "z"},      {zRL, "z"},      {zRL, "z"},      {zRL, "z"},
            {zRL, "z"},      {zRL, "z"},      {zRL, "z"},      {zRL, "z"},
            {zRR, "z"},      {zRR, "z"},      {zRR, "z"},      {zRR, "z"},
            {zRR, "z"},      {zRR, "z"},      {zRR, "z"},      {zRR, "z"},
            {zSLA, "z"},     {zSLA, "z"},     {zSLA, "z"},     {zSLA, "z"},
            {zSLA, "z"},     {zSLA, "z"},     {zSLA, "z"},     {zSLA, "z"},
            {zSRA, "z"},     {zSRA, "z"},     {zSRA, "z"},     {zSRA, "z"},
            {zSRA, "z"},     {zSRA, "z"},     {zSRA, "z"},     {zSRA, "z"},
            {zSLL, "z"},     {zSLL, "z"},     {zSLL, "z"},     {zSLL, "z"},
            {zSLL, "z"},     {zSLL, "z"},     {zSLL, "z"},     {zSLL, "z"},
            {zSRL, "z"},     {zSRL, "z"},     {zSRL, "z"},     {zSRL, "z"},
            {zSRL, "z"},     {zSRL, "z"},     {zSRL, "z"},     {zSRL, "z"},
            {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},
            {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},
            {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},
            {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},
            {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},
            {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},
            {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},
            {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},
            {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},
            {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},
            {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},
            {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},
            {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},
            {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},
            {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},
            {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},  {zBIT, "s, z"},
            {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},
            {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},
            {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},
            {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},
            {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},
            {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},
            {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},
            {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},
            {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},
            {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},
            {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},
            {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},
            {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},
            {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},
            {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},
            {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},  {zRES, "s, z"},
            {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},
            {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},
            {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},
            {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},
            {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},
            {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},
            {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},
            {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},
            {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},
            {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},
            {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},
            {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},
            {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},
            {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},
            {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},
            {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"},  {zSET, "s, z"}
        };
        Desc ddfd_prefix[0x100] = {
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zDB, "?"},      {zADD, "x, p"},  {zDB, "?"},      {zDB, "?"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zDB, "?"},      {zADD, "x, p"},  {zDB, "?"},      {zDB, "?"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zDB, "?"},      {zLD, "x, w"},   {zLD, "(w), x"}, {zINC, "x"},
            {zINC, "xh"},    {zDEC, "xh"},    {zLD, "xh, b"},  {zDB, "?"},
            {zDB, "?"},      {zADD, "x, x"},  {zLD, "x, (w)"}, {zDEC, "x"},
            {zINC, "xl"},    {zDEC, "xl"},    {zLD, "xl, b"},  {zDB, "?"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zINC, "X"},     {zDEC, "X"},     {zLD, "X, b"},   {zDB, "?"},
            {zDB, "?"},      {zADD, "x, p"},  {zDB, "?"},      {zDB, "?"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zLD, "y, xh"},  {zLD, "y, xl"},  {zLD, "y, X"},   {zDB, "?"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zLD, "y, xh"},  {zLD, "y, xl"},  {zLD, "y, X"},   {zDB, "?"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zLD, "y, xh"},  {zLD, "y, xl"},  {zLD, "y, X"},   {zDB, "?"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zLD, "y, xh"},  {zLD, "y, xl"},  {zLD, "y, X"},   {zDB, "?"},
            {zLD, "xh, z"},  {zLD, "xh, z"},  {zLD, "xh, z"},  {zLD, "xh, z"},
            {zLD, "xh, xh"}, {zLD, "xh, xl"}, {zLD, "y, X"},   {zLD, "xh, z"},
            {zLD, "xl, z"},  {zLD, "xl, z"},  {zLD, "xl, z"},  {zLD, "xl, z"},
            {zLD, "xl, xh"}, {zLD, "xl, xl"}, {zLD, "y, X"},   {zLD, "xl, z"},
            {zLD, "X, z"},   {zLD, "X, z"},   {zLD, "X, z"},   {zLD, "X, z"},
            {zLD, "X, z"},   {zLD, "X, z"},   {zDB, "?"},      {zLD, "X, z"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zLD, "y, xh"},  {zLD, "y, xl"},  {zLD, "y, X"},   {zDB, "?"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zADD, "A, xh"}, {zADD, "A, xl"}, {zADD, "A, X"},  {zDB, "?"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zADC, "A, xh"}, {zADC, "A, xl"}, {zADC, "A, X"},  {zDB, "?"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zSUB, "xh"},    {zSUB, "xl"},    {zSUB, "X"},     {zDB, "?"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zSBC, "A, xh"}, {zSBC, "A, xl"}, {zSBC, "A, X"},  {zDB, "?"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zAND, "xh"},    {zAND, "xl"},    {zAND, "X"},     {zDB, "?"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zXOR, "xh"},    {zXOR, "xl"},    {zXOR, "X"},     {zDB, "?"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zOR, "xh"},     {zOR, "xl"},     {zOR, "X"},      {zDB, "?"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zCP, "xh"},     {zCP, "xl"},     {zCP, "X"},      {zDB, "?"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, NULL},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zDB, "?"},      {zPOP, "x"},     {zDB, "?"},      {zEX, "(SP), x"},
            {zDB, "?"},      {zPUSH, "x"},    {zDB, "?"},      {zDB, "?"},
            {zDB, "?"},      {zJP, "(x)"},    {zDB, "?"},      {zDB, "?"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"},
            {zDB, "?"},      {zLD, "SP, x"},  {zDB, "?"},      {zDB, "?"},
            {zDB, "?"},      {zDB, "?"},      {zDB, "?"},      {zDB, "?"}
        };
        Desc ed_prefix[0x100] = {
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zIN, "y, (C)"},  {zOUT, "(C), y"}, {zSBC, "HL, p"},  {zLD, "(w), p"},
            {zNEG, NULL},     {zRETN, NULL},    {zIM, "0"},       {zLD, "I, A"},
            {zIN, "y, (C)"},  {zOUT, "(C), y"}, {zADC, "HL, p"},  {zLD, "p, (w)"},
            {zNEG, NULL},     {zRETI, NULL},    {zIM, "0"},       {zLD, "R, A"},
            {zIN, "y, (C)"},  {zOUT, "(C), y"}, {zSBC, "HL, p"},  {zLD, "(w), p"},
            {zNEG, NULL},     {zRETN, NULL},    {zIM, "1"},       {zLD, "A, I"},
            {zIN, "y, (C)"},  {zOUT, "(C), y"}, {zADC, "HL, p"},  {zLD, "p, (w)"},
            {zNEG, NULL},     {zRETI, NULL},    {zIM, "2"},       {zLD, "A, R"},
            {zIN, "y, (C)"},  {zOUT, "(C), y"}, {zSBC, "HL, p"},  {zLD, "(w), p"},
            {zNEG, NULL},     {zRETN, NULL},    {zIM, "0"},       {zRRD, "A, (HL)"},
            {zIN, "y, (V)"},  {zOUT, "(C), y"}, {zADC, "HL, p"},  {zLD, "p, (w)"},
            {zNEG, NULL},     {zRETI, NULL},    {zIM, "0"},       {zRLD, "A, (HL)"},
            {zIN, "0, (C)"},  {zOUT, "(C), 0"}, {zSBC, "HL, p"},  {zLD, "(w), p"},
            {zNEG, NULL},     {zRETN, NULL},    {zIM, "1"},       {zDB, "?"},
            {zIN, "y, (C)"},  {zOUT, "(C), y"}, {zADC, "HL, p"},  {zLD, "p, (w)"},
            {zNEG, NULL},     {zRETI, NULL},    {zIM, "2"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zLDI, NULL},     {zCPI, NULL},     {zINI, NULL},     {zOUTI, NULL},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zLDD, NULL},     {zCPD, NULL},     {zIND, NULL},     {zOUTD, NULL},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zLDIR, NULL},    {zCPIR, NULL},    {zINIR, NULL},    {zOTIR, NULL},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zLDDR, NULL},    {zCPDR, NULL},    {zINDR, NULL},    {zOTDR, NULL},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"},
            {zDB, "?"},       {zDB, "?"},       {zDB, "?"},       {zDB, "?"}
        };
        Desc ddfdcb_prefix[0x100] = {
            {zRLC,"Y, z"},    {zRLC,"Y, z"},    {zRLC,"Y, z"},    {zRLC,"Y, z"},
            {zRLC,"Y, z"},    {zRLC,"Y, z"},    {zRLC,"Y"},       {zRLC,"Y, z"},
            {zRRC,"Y, z"},    {zRRC,"Y, z"},    {zRRC,"Y, z"},    {zRRC,"Y, z"},
            {zRRC,"Y, z"},    {zRRC,"Y, z"},    {zRRC,"Y"},       {zRRC,"Y, z"},
            {zRL,"Y, z"},     {zRL,"Y, z"},     {zRL,"Y, z"},     {zRL,"Y, z"},
            {zRL,"Y, z"},     {zRL,"Y, z"},     {zRL,"Y"},        {zRL,"Y, z"},
            {zRR,"Y, z"},     {zRR,"Y, z"},     {zRR,"Y, z"},     {zRR,"Y, z"},
            {zRR,"Y, z"},     {zRR,"Y, z"},     {zRR,"Y"},        {zRR,"Y, z"},
            {zSLA,"Y, z"},    {zSLA,"Y, z"},    {zSLA,"Y, z"},    {zSLA,"Y, z"},
            {zSLA,"Y, z"},    {zSLA,"Y, z"},    {zSLA,"Y"},       {zSLA,"Y, z"},
            {zSRA,"Y, z"},    {zSRA,"Y, z"},    {zSRA,"Y, z"},    {zSRA,"Y, z"},
            {zSRA,"Y, z"},    {zSRA,"Y, z"},    {zSRA,"Y"},       {zSRA,"Y, z"},
            {zSLL,"Y, z"},    {zSLL,"Y, z"},    {zSLL,"Y, z"},    {zSLL,"Y, z"},
            {zSLL,"Y, z"},    {zSLL,"Y, z"},    {zSLL,"Y"},       {zSLL,"Y, z"},
            {zSRL,"Y, z"},    {zSRL,"Y, z"},    {zSRL,"Y, z"},    {zSRL,"Y, z"},
            {zSRL,"Y, z"},    {zSRL,"Y, z"},    {zSRL,"Y"},       {zSRL,"Y, z"},
            {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"},
            {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"}, {zBIT,"s, Y"},    {zBIT,"s, Y, z"},
            {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"},
            {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"}, {zBIT,"s, Y"},    {zBIT,"s, Y, z"},
            {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"},
            {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"}, {zBIT,"s, Y"},    {zBIT,"s, Y, z"},
            {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"},
            {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"}, {zBIT,"s, Y"},    {zBIT,"s, Y, z"},
            {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"},
            {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"}, {zBIT,"s, Y"},    {zBIT,"s, Y, z"},
            {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"},
            {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"}, {zBIT,"s, Y"},    {zBIT,"s, Y, z"},
            {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"},
            {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"}, {zBIT,"s, Y"},    {zBIT,"s, Y, z"},
            {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"},
            {zBIT,"s, Y, z"}, {zBIT,"s, Y, z"}, {zBIT,"s, Y"},    {zBIT,"s, Y, z"},
            {zRES,"s, Y, z"}, {zRES,"s, Y, z"}, {zRES,"s, Y, z"}, {zRES,"s, Y, z"},
            {zRES,"s, Y, z"}, {zRES,"s, Y, z"}, {zRES,"s, Y"},    {zRES,"s, Y, z"},
            {zRES,"s, Y, z"}, {zRES,"s, Y, z"}, {zRES,"s, Y, z"}, {zRES,"s, Y, z"},
            {zRES,"s, Y, z"}, {zRES,"s, Y, z"}, {zRES,"s, Y"},    {zRES,"s, Y, z"},
            {zRES,"s, Y, z"}, {zRES,"s, Y, z"}, {zRES,"s, Y, z"}, {zRES,"s, Y, z"},
            {zRES,"s, Y, z"}, {zRES,"s, Y, z"}, {zRES,"s, Y"},    {zRES,"s, Y, z"},
            {zRES,"s, Y, z"}, {zRES,"s, Y, z"}, {zRES,"s, Y, z"}, {zRES,"s, Y, z"},
            {zRES,"s, Y, z"}, {zRES,"s, Y, z"}, {zRES,"s, Y"},    {zRES,"s, Y, z"},
            {zRES,"s, Y, z"}, {zRES,"s, Y, z"}, {zRES,"s, Y, z"}, {zRES,"s, Y, z"},
            {zRES,"s, Y, z"}, {zRES,"s, Y, z"}, {zRES,"s, Y"},    {zRES,"s, Y, z"},
            {zRES,"s, Y, z"}, {zRES,"s, Y, z"}, {zRES,"s, Y, z"}, {zRES,"s, Y, z"},
            {zRES,"s, Y, z"}, {zRES,"s, Y, z"}, {zRES,"s, Y"},    {zRES,"s, Y, z"},
            {zRES,"s, Y, z"}, {zRES,"s, Y, z"}, {zRES,"s, Y, z"}, {zRES,"s, Y, z"},
            {zRES,"s, Y, z"}, {zRES,"s, Y, z"}, {zRES,"s, Y"},    {zRES,"s, Y, z"},
            {zRES,"s, Y, z"}, {zRES,"s, Y, z"}, {zRES,"s, Y, z"}, {zRES,"s, Y, z"},
            {zRES,"s, Y, z"}, {zRES,"s, Y, z"}, {zRES,"s, Y"},    {zRES,"s, Y, z"},
            {zSET,"s, Y, z"}, {zSET,"s, Y, z"}, {zSET,"s, Y, z"}, {zSET,"s, Y, z"},
            {zSET,"s, Y, z"}, {zSET,"s, Y, z"}, {zSET,"s, Y"},    {zSET,"s, Y, z"},
            {zSET,"s, Y, z"}, {zSET,"s, Y, z"}, {zSET,"s, Y, z"}, {zSET,"s, Y, z"},
            {zSET,"s, Y, z"}, {zSET,"s, Y, z"}, {zSET,"s, Y"},    {zSET,"s, Y, z"},
            {zSET,"s, Y, z"}, {zSET,"s, Y, z"}, {zSET,"s, Y, z"}, {zSET,"s, Y, z"},
            {zSET,"s, Y, z"}, {zSET,"s, Y, z"}, {zSET,"s, Y"},    {zSET,"s, Y, z"},
            {zSET,"s, Y, z"}, {zSET,"s, Y, z"}, {zSET,"s, Y, z"}, {zSET,"s, Y, z"},
            {zSET,"s, Y, z"}, {zSET,"s, Y, z"}, {zSET,"s, Y"},    {zSET,"s, Y, z"},
            {zSET,"s, Y, z"}, {zSET,"s, Y, z"}, {zSET,"s, Y, z"}, {zSET,"s, Y, z"},
            {zSET,"s, Y, z"}, {zSET,"s, Y, z"}, {zSET,"s, Y"},    {zSET,"s, Y, z"},
            {zSET,"s, Y, z"}, {zSET,"s, Y, z"}, {zSET,"s, Y, z"}, {zSET,"s, Y, z"},
            {zSET,"s, Y, z"}, {zSET,"s, Y, z"}, {zSET,"s, Y"},    {zSET,"s, Y, z"},
            {zSET,"s, Y, z"}, {zSET,"s, Y, z"}, {zSET,"s, Y, z"}, {zSET,"s, Y, z"},
            {zSET,"s, Y, z"}, {zSET,"s, Y, z"}, {zSET,"s, Y"},    {zSET,"s, Y, z"},
            {zSET,"s, Y, z"}, {zSET,"s, Y, z"}, {zSET,"s, Y, z"}, {zSET,"s, Y, z"},
            {zSET,"s, Y, z"}, {zSET,"s, Y, z"}, {zSET,"s, Y"},    {zSET,"s, Y, z"}
        };
};
